# Generated by Django 4.1.2 on 2023-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mwe", "0005_alter_xpathquery_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalform",
            name="dcmid",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
