# Generated by Django 4.1.2 on 2022-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0004_component_contains_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='contains_metadata',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='public',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='sentence_tokenized',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='sentences_have_labels',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='word_tokenized',
        ),
        migrations.AddField(
            model_name='treebank',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
