# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ['3.8']
        node-version: ['12.x']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.python-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        npm install
    - name: Build
      run: |
        npm run build
    - name: Migrate
      run: |
        npm run migrate
    - name: Lint
      run: |
        # npm run lint
        npm run lint:backend
    - name: Run tests
      run: |
        npm run start:backend &
        chromedriver --version
        npm run test
